/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import DTO.UsuarioDTO;
import DAO.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.awt.Button;

/**
 *
 * @author jaine
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        entrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login FamintOs");
        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(590, 425));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(821, 500));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/famintos.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 20, 310, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 120, 90, 29);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(50, 160, 260, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 80, 29);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha);
        txtSenha.setBounds(50, 250, 260, 30);

        entrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        entrar.setText("ENTRAR");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel1.add(entrar);
        entrar.setBounds(110, 320, 120, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logofamintos.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 0, 460, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        Logar();
    }//GEN-LAST:event_entrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void Logar() {

        try {
            String email = txtEmail.getText();
            String senha = String.valueOf(txtSenha.getPassword());

            UsuarioDTO objuser = new UsuarioDTO();
            objuser.setEmail(email);
            objuser.setSenha(senha);

            UsuarioDAO objuserdao = new UsuarioDAO();
            ResultSet rsuserdao = objuserdao.autenticarUser(objuser);
            if (rsuserdao.next()) {
                String cargo = rsuserdao.getString(6);
                String user = rsuserdao.getString(1);
                String Nome = user.split(" ")[0];
                String labelUser=Nome+" ("+cargo+")";
                objuser.setGuardar_user(labelUser);
                Menu mn = new Menu();
                if (cargo.equals("Administrador")){
                    mn.setVisible(true);
                    mn.txtUsuario.setText(Nome + " (Administrador)");
                    mn.btnCadastrar.setEnabled(true);
                    mn.btnGerenciar.setEnabled(true);
                    mn.btnControle.setEnabled(true);
                    mn.btnPratos.setEnabled(true);
                    mn.btnPedidos.setEnabled(true);
                    dispose();
                } else if (cargo.equals("Gerente")) {
                    mn.setVisible(true);
                    mn.txtUsuario.setText(Nome + " (Gerente)");
                    mn.btnCadastrar.setEnabled(true);
                    mn.btnGerenciar.setEnabled(true);
                    mn.btnControle.setEnabled(true);
                    mn.btnPratos.setEnabled(true);
                    mn.btnPedidos.setEnabled(false);
                    dispose();
                } else if (cargo.equals("Chef")) {
                    mn.setVisible(true);
                    mn.txtUsuario.setText(Nome + " (Chef)");
                    mn.btnPratos.setEnabled(true);
                    mn.btnPedidos.setEnabled(true);
                    dispose();
                } else if (cargo.equals("Cozinheiro")) {
                    mn.setVisible(true);
                    mn.txtUsuario.setText(Nome + " (Cozinheiro)");
                    mn.btnPedidos.setEnabled(true);
                    dispose();
                } else if (cargo.equals("Garçom")) {
                    mn.setVisible(true);
                    mn.txtUsuario.setText(Nome + " (Garçom)");
                    mn.btnPedidos.setEnabled(true);
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email ou Senha Incorretos!");
            }

        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, erro);
        }
    }

    
}
