/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tela;

import static java.awt.Color.gray;
import static java.awt.Color.white;

/**
 *
 * @author user3
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Gerente
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGerenciar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnControle = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnPratos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setMinimumSize(new java.awt.Dimension(619, 598));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/famintos.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 20, 300, 60);

        txtUsuario.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(300, 80, 310, 30);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_______________________");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 140, 320, 29);

        btnGerenciar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnGerenciar.setText("GERENCIAR ESTOQUE");
        btnGerenciar.setEnabled(false);
        btnGerenciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGerenciar);
        btnGerenciar.setBounds(100, 260, 410, 29);

        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnCadastrar.setText("CADASTRAR FUNCIONÁRIO");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(100, 210, 410, 29);

        btnControle.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnControle.setText("RELATÓRIOS");
        btnControle.setEnabled(false);
        btnControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnControleActionPerformed(evt);
            }
        });
        jPanel1.add(btnControle);
        btnControle.setBounds(100, 310, 410, 29);

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(200, 510, 100, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText(" Conectado como ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 80, 300, 30);

        btnPratos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPratos.setText("INCLUIR E EXCLUIR PRATOS");
        btnPratos.setEnabled(false);
        btnPratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPratosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPratos);
        btnPratos.setBounds(100, 360, 410, 29);

        btnPedidos.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnPedidos.setText("VER PEDIDOS PENDENTES");
        btnPedidos.setEnabled(false);
        btnPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnPedidos);
        btnPedidos.setBounds(100, 410, 410, 29);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" MENU PRINCIPAL");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 130, 220, 29);

        jButton2.setText("(X) SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 510, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 620, 600);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerenciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarActionPerformed
        String Nome = txtUsuario.getText();
        Estoque cd = new Estoque();
        cd.txtUser.setText(Nome);
        dispose();
        cd.setVisible(true);
    }//GEN-LAST:event_btnGerenciarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String Nome = txtUsuario.getText();
        Cadastro cd = new Cadastro();
        cd.txtUser.setText(Nome);
        if (cd.txtUser.getText().contains("Administrador")) {
            cd.txtUser.setBackground(white);
        } else {
            cd.txtUser.setBackground(gray);
        }
        dispose();
        cd.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControleActionPerformed
        Relatorios rlt = new Relatorios();
        String Nome = txtUsuario.getText();
        rlt.txtUser.setText(Nome);
        dispose();
        rlt.setVisible(true);
    }//GEN-LAST:event_btnControleActionPerformed

    private void btnPratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPratosActionPerformed
        PratosnCardapio pc = new PratosnCardapio();
        String Nome = txtUsuario.getText();
        pc.txtUser.setText(Nome);
        dispose();
        pc.setVisible(true);
    }//GEN-LAST:event_btnPratosActionPerformed

    private void btnPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidosActionPerformed
        PedidosG pd = new PedidosG();
        String Nome = txtUsuario.getText();
        pd.txtUser.setText(Nome);
        dispose();
        pd.setVisible(true);
    }//GEN-LAST:event_btnPedidosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login lgn = new Login();
        lgn.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCadastrar;
    public javax.swing.JButton btnControle;
    public javax.swing.JButton btnGerenciar;
    public javax.swing.JButton btnPedidos;
    public javax.swing.JButton btnPratos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
    public void chamar() {
        String cargo = txtUsuario.getText();
        if (cargo.contains("Gerente")) {
            btnCadastrar.setEnabled(true);
            btnGerenciar.setEnabled(true);
            btnControle.setEnabled(true);
            btnPratos.setEnabled(true);
            btnPedidos.setEnabled(false);
        } else if (cargo.contains("Chef")) {
            btnPratos.setEnabled(true);
            btnPedidos.setEnabled(true);
        } else if (cargo.contains("Cozinheiro")) {
            btnPedidos.setEnabled(true);
        } else if (cargo.contains("Garçom")) {
            btnPedidos.setEnabled(true);
        } else if (cargo.contains("Administrador")) {
            btnCadastrar.setEnabled(true);
            btnGerenciar.setEnabled(true);
            btnControle.setEnabled(true);
            btnPratos.setEnabled(true);
            btnPedidos.setEnabled(true);
        }
    }

}
